---
# tasks file for roles/docker

- name: Installing Docker
  dnf: name=docker-engine state=present

- name: Enable autostart Docker at boot and starting Docker
  service: name=docker enabled=yes state=started

- name: Installing docker-py module
  pip: name=docker-py version=1.9.0

- name: Installing libselinux-python module
  dnf: name=libselinux-python state=present